apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod

spec:
  containers:
    - name: two-tier-app-ctr 
      image: pardeshiumesh23/flaskapp:latest
      env:
        - name: MYSQL_HOST
          value: "mysql" #later update it with mysql pod ip address
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
      ports:
        - containerPort: 5000
      imagePullPolicy: Always

