apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-deployment
  labels:
    app: two-tier-app #where ever this labels is matched then this deployment will run for it

spec:
  replicas: 4
  selector: #this is used to match the labels   
    matchLabels: 
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app 

    spec:
      containers:
        - name: two-tier-app-ctr 
          image: pardeshiumesh23/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "mysql" #later update it with mysql pod ip address
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always

